# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: erc721indexer
description: ERC-721 indexer

networks:
  - id: 1
    start_block: 22492800
    end_block: 22492810
    contracts:
      - name: ERC721
        handler: ./src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
            field_selection:
              transaction_fields:
                - hash

  - id: 11155111  # Sepolia
    start_block: 0
    contracts:
      - name: ArtMetadataUpdater
        address: 
        - 0xFAA5869c1d027E48a2618440a06E90656F16Bb3F
        handler: src/EventHandlers.ts
        events:
          - event: CreatorContextUpdated(string artId, string creatorContextURI, address updatedBy)
          - event: AwakeningURIUpdated(string artId, string awakeningURI, address updatedBy)  
          - event: JourneysURIUpdated(string artId, string journeysURI, address updatedBy)              
# Unordered multichain mode allows you to index events from multiple chains
# in realtime but doesn't guarentee ordering between chains
# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
# Preload optimisation makes your indexer much faster.
# But be aware that your handlers will run twice,
# so make sure to use Effect API for external calls.
preload_handlers: true
# Address format for Ethereum addresses: 'checksum' or 'lowercase'
# using lowercase addresses is slightly faster
address_format: lowercase