# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: stream-of-consciousness
description: stream-of-consciousness indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
networks:
  - id: 1 # Ethereum
    start_block: 0
    contracts:
      - name: ERC721 #A reference to the wildcard contract definition
        handler: ./src/EventHandlers.ts
        events: 
        - event: Transfer(address indexed from, address indexed to, uint256 value)
  - id: 8453 # Base
    start_block: 0
    contracts:
      - name: ERC721 #A reference to the wildcard contract definition
        handler: ./src/EventHandlers.ts
        events:
        - event: Transfer(address indexed from, address indexed to, uint256 value) 
  - id: 7777777 # Zora
    start_block: 0
    contracts:
      - name: ERC721 #A reference to the wildcard contract definition
        handler: ./src/EventHandlers.ts
        events: 
        - event: Transfer(address indexed from, address indexed to, uint256 value)
# Unordered multichain mode allows you to index events from multiple chains
# in realtime but doesn't guarentee ordering between chains
# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
# Preload optimisation makes your indexer much faster.
# But be aware that your handlers will run twice,
# so make sure to use Effect API for external calls.
preload_handlers: true
# Address format for Ethereum addresses: 'checksum' or 'lowercase'
# using lowercase addresses is slightly faster
address_format: lowercase